name = "api-proxy-manager"
main = "src/index.js"
compatibility_date = "2025-07-22"

[env.production]
name = "api-proxy-manager"

[[env.production.kv_namespaces]]
binding = "APIPROXY_PROJECTS_KV"
id = "2f77fc2403414a889b6abd0363596a36"

[[env.production.kv_namespaces]]
binding = "APIPROXY_SECRETS_KV"
id = "8ae4fa74fcf64fdaabde8e7c94746942"

[vars]
ENVIRONMENT = "production"